//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineralAirways.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DAPEntities : DbContext
    {
        public DAPEntities()
            : base("name=DAPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asientos> Asientos { get; set; }
        public virtual DbSet<Aviones> Aviones { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Pasajeros> Pasajeros { get; set; }
        public virtual DbSet<ReservasVuelos> ReservasVuelos { get; set; }
        public virtual DbSet<Rutas> Rutas { get; set; }
        public virtual DbSet<Tramos> Tramos { get; set; }
        public virtual DbSet<Vuelos> Vuelos { get; set; }
    }
}
