//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineralAirways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasajeros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pasajeros()
        {
            this.ReservasVuelos = new HashSet<ReservasVuelos>();
        }
    
        public int PasajeroID { get; set; }
        public string Rut { get; set; }
        public string Nombres { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string Cargo { get; set; }
        public string EMail { get; set; }
        public string AsientoAsignado { get; set; }
        public bool EsEjecutivo { get; set; }
        public Nullable<int> ClienteID { get; set; }
        public string Pass { get; set; }
        public int TipoUsuario { get; set; }
        public bool PrimerLogeo { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservasVuelos> ReservasVuelos { get; set; }
    }
}
