//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MineralAirways.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservasVuelos
    {
        public int ReservaVueloID { get; set; }
        public int AvionID { get; set; }
        public int TramoID { get; set; }
        public Nullable<int> PasajeroID { get; set; }
        public Nullable<bool> ConfirmacionAsiento { get; set; }
        public Nullable<System.DateTime> FechaHoraConfirmación { get; set; }
        public Nullable<System.DateTime> FechaHoraCancelacion { get; set; }
        public int VueloID { get; set; }
        public int AsientoID { get; set; }
    
        public virtual Asientos Asientos { get; set; }
        public virtual Aviones Aviones { get; set; }
        public virtual Pasajeros Pasajeros { get; set; }
        public virtual Tramos Tramos { get; set; }
        public virtual Vuelos Vuelos { get; set; }
    }
}
