//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmailMensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailMensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EmailMensajes", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;td style=&quot;font-family: Arial,Helvetica,sans-serif; font-size: 18px; color: #666;&quot;&gt;
        ///			Estimado: [NOMBRE_USUARIO]
        ///		&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td style=&quot;padding: 20px 0 30px 0; font-family: Arial,Helvetica,sans-serif; font-size: 14px;color: #666;&quot;&gt;
        ///			&lt;p&gt;Informamos que con fecha [FECHA_ENVIO], usted ha &lt;strong&gt;cancelado&lt;/strong&gt; exitosamente la reserva del vuelo, con los siguientes datos:&lt;/p&gt;
        ///			&lt;p&gt;Número Vuelo: [NUMERO_VUELO]&lt;/p&gt;
        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CancelacionReservaVuelo {
            get {
                return ResourceManager.GetString("CancelacionReservaVuelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;td style=&quot;font-family: Arial,Helvetica,sans-serif; font-size: 18px; color: #666;&quot;&gt;
        ///			Estimado: [NOMBRE_USUARIO]
        ///		&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td style=&quot;padding: 20px 0 30px 0; font-family: Arial,Helvetica,sans-serif; font-size: 14px;color: #666;&quot;&gt;
        ///			&lt;p&gt;Informamos que con fecha [FECHA_ENVIO], usted ha solictado la recuperación de su contraseña a través del sistema.&lt;/p&gt;
        ///			&lt;p&gt;&lt;strong&gt;Contraseña: [CLAVE]&lt;/strong&gt;&lt;/p&gt;						
        ///			&lt;p&gt;Se  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string RecuperarClave {
            get {
                return ResourceManager.GetString("RecuperarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;100%&quot;&gt;
        ///	&lt;tr&gt;
        ///		&lt;td style=&quot;font-family: Arial,Helvetica,sans-serif; font-size: 18px; color: #666;&quot;&gt;
        ///			Estimado: [NOMBRE_USUARIO]
        ///		&lt;/td&gt;
        ///	&lt;/tr&gt;
        ///	&lt;tr&gt;
        ///		&lt;td style=&quot;padding: 20px 0 30px 0; font-family: Arial,Helvetica,sans-serif; font-size: 14px;color: #666;&quot;&gt;
        ///			&lt;p&gt;Informamos que con fecha [FECHA_ENVIO], usted ha registrado exitosamente la reserva del vuelo, con los siguientes datos:&lt;/p&gt;
        ///			&lt;p&gt;Número Vuelo: [NUMERO_VUELO]&lt;/p&gt;
        ///			&lt;p&gt;Fecha Sali [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ReservarVuelo {
            get {
                return ResourceManager.GetString("ReservarVuelo", resourceCulture);
            }
        }
    }
}
